Feat(api): Created classes Role, Permission and Essay
Redacao-Brilhante/RB pull request #2
Opened 2022-05-19 20:39 UTC by felipeandersonr

* Created class Essay 
* Added and updated user class attributes
* Created classes Role and Permission
* Added permissions and roles

2022-05-19 20:51 UTC, Hellyson-Ferreira requested changes

2022-05-19 20:51 UTC, Hellyson-Ferreira commented on apps/api/models/user/permissions.py
> +from models.user.role import Role, Permission
Nada do que foi criado nesse arquivo foi "comitado" ele não deveria está nessa pasta, isso tudo fica no populate_database

2022-05-19 20:51 UTC, Hellyson-Ferreira commented on apps/api/models/essay/basic.py
> +    writing_skill_1: int = Column(Integer, nullable=False)
Não faz sentido que esses campos de notas das competências sejam nulos, pois a redação pode ainda não ter sido corrigido

2022-05-19 20:52 UTC, Hellyson-Ferreira requested changes

2022-05-19 20:52 UTC, Hellyson-Ferreira commented on apps/api/models/essay/basic.py
> +    writing_skill_2: int = Column(Integer, nullable=False)
Nesse caso ao invés de tu ter vai rios campos para guardar na nota poderia ser um relação com outra tabela para armazenar as notas e o que cada nota representa

2022-05-19 21:26 UTC, adryells approved these changes

2022-05-24 03:48 UTC, Hellyson-Ferreira approved these changes

2022-05-24 03:48 UTC, merged